# Generated by Django 5.2.17 on 2026-08-15 15:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_event_tracker", "0002_seed_event_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("consumer_name", models.CharField(db_index=True, max_length=255)),
                ("topic", models.CharField(db_index=True, max_length=255)),
                ("bucket_start", models.DateTimeField(db_index=True)),
                ("received", models.PositiveIntegerField(default=0)),
                ("errored", models.PositiveIntegerField(default=0)),
                ("dropped", models.PositiveIntegerField(default=0)),
                ("tickets_opened", models.PositiveIntegerField(default=0)),
                ("tickets_joined", models.PositiveIntegerField(default=0)),
                ("suppressed", models.PositiveIntegerField(default=0)),
                ("drops_by_reason", models.JSONField(blank=True, default=dict)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Ingestion Stats",
                "verbose_name_plural": "Ingestion Stats",
                "ordering": ["-bucket_start", "consumer_name", "topic"],
                "get_latest_by": "bucket_start",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("consumer_name", "topic", "bucket_start"),
                        name="event_tracker_stats_bucket_unique",
                    )
                ],
            },
        ),
    ]
