# Generated by Django 5.2.17 on 2026-08-17 13:39

# pylint: disable=new-db-field-with-default
# The default is what makes the existing rows readable: a counter row written before triage existed
# saw zero triaged messages, and that is a number, not a null. The check exists because adding a
# column with a default rewrote the whole table on PostgreSQL 10 and earlier; this app is
# PostgreSQL-only and targets versions that add a constant default as metadata alone (ADR 0003).

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_event_tracker", "0004_llm_registry"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestionstats",
            name="triage_attached",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ingestionstats",
            name="triage_errors",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ingestionstats",
            name="triaged",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
