# Generated by Django 5.2.17 on 2026-08-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_event_tracker", "0004_llm_registry"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestionstats",
            name="triage_attached",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ingestionstats",
            name="triage_errors",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ingestionstats",
            name="triaged",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
