# Generated by Django 5.2.17 on 2026-08-20 14:06

# pylint: disable=new-db-field-with-default
# The same argument migration 0005 makes for the triage counters: a counter row written before the
# enrichment resolver existed attached nothing, and that is zero rather than null. The check exists
# because adding a column with a default rewrote the whole table on PostgreSQL 10 and earlier; this
# app is PostgreSQL-only and targets versions that add a constant default as metadata alone
# (ADR 0003).

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_event_tracker", "0006_strip_unsupported_llmmodel_parameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestionstats",
            name="enriched",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ingestionstats",
            name="enrichment_misses",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
