# Generated by Django 5.2.17 on 2026-08-22 15:41

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0145_objectmetadata_assigned_object_type_cascade"),
        ("nautobot_event_tracker", "0008_mcp_registry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("status", models.CharField(db_index=True, default="running", max_length=255)),
                ("transcript", models.JSONField(blank=True, default=list)),
                ("iterations", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_tracker_agent_runs",
                        to="extras.jobresult",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resumptions",
                        to="nautobot_event_tracker.agentrun",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to="nautobot_event_tracker.eventticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Run",
                "verbose_name_plural": "Agent Runs",
                "ordering": ["-started_at"],
                "get_latest_by": "started_at",
            },
        ),
        migrations.CreateModel(
            name="AgentToolCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("arguments", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(db_index=True, default="proposed", max_length=255)),
                ("tool_fingerprint", models.CharField(blank=True, max_length=255)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("proposed_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("called_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_tool_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_calls",
                        to="nautobot_event_tracker.agentrun",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calls",
                        to="nautobot_event_tracker.mcptool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Tool Call",
                "verbose_name_plural": "Agent Tool Calls",
                "ordering": ["proposed_at"],
                "permissions": [("approve_agenttoolcall", "Can approve or deny a proposed agent tool call")],
                "get_latest_by": "proposed_at",
            },
        ),
    ]
