# Generated by Django 5.2.17 on 2026-08-23 15:07

import uuid

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
from django.db import migrations, models
from django.db.utils import ProgrammingError


class CreateVectorExtension(migrations.operations.base.Operation):
    """Create the pgvector extension, or explain why it could not be.

    Not `django.contrib.postgres.operations.CreateExtension`, and the difference is the whole
    point. `CREATE EXTENSION` needs superuser or `pg_database_owner`, and a managed PostgreSQL
    frequently grants the application user neither - so on those deployments a DBA creates the
    extension by hand, once, and this migration must then be a no-op rather than an error.

    So: look first, and only try to create it when it is genuinely absent. When that attempt is
    refused, fail with a message naming what to run, because the alternative is an operator reading
    a bare "permission denied to create extension" halfway through an upgrade.
    """

    reversible = True
    # Nothing in Django's model state depends on an extension existing.
    reduces_to_sql = False
    atomic = True

    def state_forwards(self, app_label, state):
        """No state change: an extension is a database fact, not a model one."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        """Create it if it is missing, and say something useful if that is refused."""
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("SELECT 1 FROM pg_extension WHERE extname = 'vector'")
            if cursor.fetchone():
                return
        try:
            schema_editor.execute('CREATE EXTENSION IF NOT EXISTS "vector"')
        except ProgrammingError as error:
            raise ProgrammingError(
                "nautobot_event_tracker needs the pgvector extension, and this database user may "
                "not create it. Ask a superuser to run: CREATE EXTENSION vector; and then run this "
                "migration again. See docs/admin/rag.md. "
                f"The database said: {error}"
            ) from error

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        """Deliberately a no-op.

        Dropping the extension would break anything else in the database using a vector column,
        and an app removing a database-wide facility on its own rollback is not a thing to do.
        """

    def describe(self):
        """What `sqlmigrate` and the migration plan show."""
        return "Create the pgvector extension if it is not already present"


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_event_tracker", "0009_agent_runs"),
    ]

    operations = [
        # First, because the vector column below cannot be created without it.
        CreateVectorExtension(),
        migrations.AddField(
            model_name="llmmodel",
            name="kind",
            field=models.CharField(db_index=True, default="chat", max_length=255),
        ),
        migrations.CreateModel(
            name="TicketEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField()),
                ("document", models.TextField()),
                ("dimensions", models.PositiveIntegerField()),
                ("document_fingerprint", models.CharField(max_length=255)),
                ("indexed_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="embeddings",
                        to="nautobot_event_tracker.llmmodel",
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="nautobot_event_tracker.eventticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Embedding",
                "verbose_name_plural": "Ticket Embeddings",
                "ordering": ["-indexed_at"],
                "get_latest_by": "indexed_at",
            },
        ),
    ]
