# Generated by Django 5.2.17 on 2026-08-25 02:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0145_objectmetadata_assigned_object_type_cascade"),
        ("nautobot_event_tracker", "0010_rag_embeddings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="eventticket",
            index=models.Index(fields=["created"], name="event_ticket_created_idx"),
        ),
        migrations.AddIndex(
            model_name="eventticket",
            index=models.Index(fields=["closed_at"], name="event_ticket_closed_idx"),
        ),
    ]
